default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check Blanket "#noqa"
      - id: python-check-blanket-type-ignore
        name: 'Check Blanket "#type:ignore"'
  - repo: https://github.com/crate-ci/typos
    rev: v1.1.6
    hooks:
      - id: typos
        name: Check Typos
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Format Source Code
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Sort Imports
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Lint
        additional_dependencies:
          - flake8-builtins==1.5.3
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.1.0
          - flake8-print==4.0.0
          - pep8-naming==0.12.0
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.13
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
