name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      IS_PRE_RELEASE: false
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install --user poetry
          poetry config virtualenvs.in-project true
      - name: "Check Version for Pre-releases"
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo "IS_PRE_RELEASE=true" >> $GITHUB_ENV
      - name: "Build Project"
        run: |
          poetry install
          poetry build
      - name: "Create Release on GitHub"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.IS_PRE_RELEASE }}
      - name: "Publish to PyPI"
        if: ${{ github.repository == 'queensferryme/flake8-too-many' }}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
